export const CATEGORY_ALIASES = {
  alimentacao: "Alimentação",
  alimentação: "Alimentação",
  comida: "Alimentação",
  restaurante: "Alimentação",
  mercado: "Alimentação",
  transporte: "Transporte",
  transportes: "Transporte",
  mobilidade: "Transporte",
  assinatura: "Assinaturas",
  assinaturas: "Assinaturas",
  streaming: "Assinaturas",
  viagem: "Viagem",
  viagens: "Viagem",
  hospedagem: "Viagem",
  moradia: "Moradia",
  casa: "Moradia",
  saude: "Saúde",
  saúde: "Saúde",
  farmacia: "Saúde",
  farmácia: "Saúde",
  lazer: "Lazer",
  compras: "Compras",
  trabalho: "Trabalho",
  familia: "Família",
  família: "Família",
  investimentos: "Investimentos",
  investimento: "Investimentos",
  renda_passiva: "Renda Passiva",
  renda_passiva_: "Renda Passiva",
  renda_ativa: "Renda Ativa",
};

export const INVALID_CATEGORY_ALIASES = new Set([
  "",
  "-",
  "--",
  "na",
  "n_a",
  "n/a",
  "null",
  "undefined",
  "sem_categoria",
  "sem categoria",
  "uncategorized",
]);
